NBCampFinalProject/FromPet

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/frompet/map/MapFragment.kt
- app/src/main/res/layout/fragment_map.xml
- settings.gradle
> [Map] MapFragment 지도 화면에 띄우기

- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/fragment_setting.xml
> [DESIGN]  설정 프래그먼트 스크롤 뷰 추가

- app/build.gradle
- app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatListAdapter.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
- app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
- app/src/main/java/com/example/frompet/login/data/UserModel.kt
- app/src/main/java/com/example/frompet/login/viewmodel/ChatViewModel.kt
- app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/item_chat_message.xml
- app/src/main/res/layout/item_chathome.xml
- app/src/main/res/menu/bottom_nav_menu.xml
1. 파이어스토어에 등록된 user 이미지 각 chatuserdetail에 등록
2. 파이어스토어에 등록된 user 이미지 채팅메시지화면,채팅화면에 등록
3. 파이어스토어에 uri이미지 저장해서 으로 불러오기 가능
> [Chat}채팅프래그먼트 이미지불러온거 적용입니다

- app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
- app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
- app/src/main/java/com/example/frompet/chating/ChatViewModel.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
- app/src/main/java/com/example/frompet/login/viewmodel/ChatViewModel.kt
- app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
- app/src/main/res/drawable/circle_background.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/item_chathome.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
1. 최근에 보낸 메시지순으로 채팅방 정렬
2. 실시간으로 메시지 보내면 마지막 메시지 채팅방 맨위에 뜨게 정렬
3. 채팅방에 나의 이미지 보이는 버그 수정
> [ChatFrag]챗프래그먼트 최신메시지순 정렬

- app/src/main/java/com/example/frompet/chating/ChatFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
- app/src/main/java/com/example/frompet/home/HomeFragment.kt
- app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
- app/src/main/java/com/example/frompet/map/MapFragment.kt
- app/src/main/res/layout/fragment_chat_home.xml
1. nullability 수정 앱 팅기는 현상 수정
2. 홈프래그먼트에서 하트 보내면 databse에 likeusers에 등록 하트보내기 완료
> [Fix] :nullability고려해서 간단한 수정 홈프래그먼트 ,homefrag 하트 수정

- app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
- app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
- app/src/main/java/com/example/frompet/chating/ChatViewModel.kt
- app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
- app/src/main/java/com/example/frompet/login/data/UserModel.kt
- app/src/main/res/layout/activity_chat_message.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/fragment_chat_list.xml
1.메시지어댑터 with로 적용 코드리팩토링하기전에 간단한 머지 (오류수정하고,구조잡기위해서(
> [FIX]: 메시지어댑터 with로 적용

- app/src/main/java/com/example/frompet/data/repository/user/AuthRepository.kt
- app/src/main/java/com/example/frompet/data/repository/user/BaseAuthRepository.kt
- app/src/main/java/com/example/frompet/data/repository/user/UserRepositoryImp.kt
- app/src/main/java/com/example/frompet/ui/login/LoginupViewModel.kt
- app/src/main/res/layout/activity_member_info.xml
> [Fix] : 로그인 기능 강화중

- app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
- app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
- app/src/main/res/layout/item_chathome.xml
- 채팅방목록에 채팅방의 마지막시간 띄우기 했습니다
- 한국표준시간으로 바꿨습니다
> [Chat]:채팅방 목록에 마지막메시지시간

- app/src/main/java/com/example/frompet/data/model/ChatMessage.kt
- app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
- app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
- app/src/main/res/layout/item_chathome.xml
- app/src/main/res/layout/item_date_header.xml
- app/src/main/res/values/colors.xml
- 채팅방 날짜별로 메시지 뷰타입 나눴습ㄴㅣ다
- 마지막메시지 시간 마진값수정
> [Chat] 채팅방뷰타입 세개로 날짜별로정렬

- app/src/main/java/com/example/frompet/ui/commnunity/CommunityDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
- app/src/main/res/layout/activity_community.xml
- app/src/main/res/layout/activity_community_add.xml
- app/src/main/res/layout/activity_community_detail.xml
- app/src/main/res/layout/fragment_communityhome.xml
- app/src/main/res/layout/item_coummunication.xml
- app/src/main/res/values/strings.xml
> [Community]  UI 만들었습니다

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/frompet/data/repository/message/MessageRepositoryImpl.kt
- app/src/main/java/com/example/frompet/ui/chat/activity/ChatClickUserDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
- app/src/main/java/com/example/frompet/ui/chat/activity/ChatUserDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
- app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
- app/src/main/java/com/example/frompet/ui/map/MapMakerBorder.kt
- app/src/main/java/com/example/frompet/ui/map/MapUserDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
- app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
- app/src/main/res/layout/activity_chat_click_user_detail.xml
- app/src/main/res/layout/activity_chat_message.xml
- app/src/main/res/layout/activity_chat_user_detail.xml
- app/src/main/res/layout/activity_map_user_detail.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/fragment_chat_list.xml
- app/src/main/res/layout/fragment_home_bottom_sheet_dialog.xml
- app/src/main/res/layout/item_chatlist.xml
- app/src/main/res/layout/item_date_header.xml
- app/src/main/res/layout/item_home.xml
- app/src/main/res/layout/item_my_message.xml
- app/src/main/res/layout/item_other_message.xml
- app/src/main/res/values/strings.xml
1. 채팅방삭제했을때 메시지 빈값일때 마지막시간""로표시
2. 사진보냈을 때 라트스메시지 텍스트"사진"으로표시
3. 맵프래그먼트 프로필마커띄우기
> [Chat]사진보냈을때 마지막메시지"사진"의로표시

- app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
- app/src/main/res/layout/activity_community_add.xml
- app/src/main/res/layout/activity_community_detail.xml
- app/src/main/res/layout/fragment_communityhome.xml
- app/src/main/res/layout/item_community.xml
- app/src/main/res/layout/item_coummunication.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values/strings.xml
> [FIX] 커뮤니티 연결, UI 수정하였습니다.

- app/src/main/java/com/example/frompet/data/model/CommunityData.kt
- app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
- app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
> [커뮤니티] 커뮤니티 연결 수정 중입니다.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/frompet/MainActivity.kt
- app/src/main/java/com/example/frompet/data/model/FCMNotificatuonData.kt
- app/src/main/java/com/example/frompet/data/repository/fcm/FCMNotificationRepository.kt
- app/src/main/java/com/example/frompet/data/repository/fcm/FCMNotificationRepositoryImpl.kt
- app/src/main/java/com/example/frompet/data/repository/firebase/MyFirebaseMessagingService.kt
- app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
- app/src/main/java/com/example/frompet/ui/setting/FCMTokenManagerViewModel.kt
- app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
- app/src/main/java/com/example/frompet/ui/setting/fcm/FCMNotificationViewModel.kt
- app/src/main/java/com/example/frompet/ui/setting/fcm/FCMTokenManager.kt
- app/src/main/java/com/example/frompet/ui/setting/fcm/MyFirebaseMessagingService.kt
- app/src/main/res/layout/activity_chat_click_user_detail.xml
- app/src/main/res/layout/activity_chat_user_detail.xml
- app/src/main/res/layout/activity_map_user_detail.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/fragment_chat_list.xml
1. 홈프래그먼트에서 상대방좋아요 했을때 상대방 애뮬에 푸쉬알람
2. MVVM패턴적용
3. key는 아직 안숨김..숨겨야함...
> [FCM] 홈에서 유저에게 좋아요 보냈을때 상대방알람

- app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
- app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
- app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
- app/src/main/java/com/example/frompet/ui/login/MemberInfoAdapter.kt
- app/src/main/res/layout/activity_member_info.xml
- app/src/main/res/layout/item_info_type.xml
회원정보 반려동물 종류를 스피넷으로 설정
데이터는 아직 저장 안됨
> [feat] 회원정보 반려동물 종류 커스텀 스피넷 

- app/src/main/res/drawable/icon_google.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_sing_up.xml
- app/src/main/res/layout/fragment_chat_home.xml
- app/src/main/res/layout/fragment_chat_list.xml
> [DESIGN] 전체적인 ui 수정 중

- app/src/main/java/com/example/frompet/data/repository/chat/ChatRepositoryImpl.kt
- app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
- app/src/main/java/com/example/frompet/ui/chat/fragment/ChatHomeFragment.kt
- app/src/main/java/com/example/frompet/ui/chat/fragment/ChatLikeListFragment.kt
- app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
- app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_setting.xml
- app/src/main/res/values/styles.xml
> [FIX]다양한오류.간단한디자인

- app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
- app/src/main/java/com/example/frompet/ui/setting/SettingViewModel.kt
- app/src/main/res/drawable/round_background.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/sample.xml
- app/src/main/res/layout/sample2.xml
> [셋팅 프로필 액티비티] 디자인 수정

- app/src/main/java/com/example/frompet/data/model/CommunityData.kt
- app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
- app/src/main/res/layout/activity_community_detail.xml
- app/src/main/res/values/colors.xml
- 유저디테일 상단부분 작성자 프로필,펫네임,작성시간 뜨게 수정했습니다
- 간격수정 했습니다(제목이나,내용길어지면 match로 하고 마진값줘야지 양옆에 딱붙게 안나옵니다)
> [community] : 유저디테일 상당부분

- app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
- app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
- app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
- app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
1.댓글 프로필, 이름, 시간 뜨게 했습니다.
2.펫 성별,종류 아이콘 위치 변경했습니다.
> [커뮤니티 디테일, 셋팅 프로필] 댓글 정보 뜨게 변경, 펫 성별,종류 아이콘 위치 변경
